module.exports = {
    characters: [
        {
            alphabet: 'latin',
            start: 97,
            end: 122,
        },
        {
            alphabet: 'bopomofo/mandarin',
            start: 12549,
            end: 12588
        },
        {
            alphabet: 'katakana',
            start: 12449,
            end: 12542
        },
        {
            alphabet: 'cyrillic',
            start: 1072,
            end: 1119,
        },
        {
            alphabet: 'hangul/korean',
            start: 12593,
            end: 12686
        },
        {
            alphabet: 'arabic',
            start: 1575,
            end: 1610,
        },
        {
            alphabet: 'armenian',
            start: 1377,
            end: 1414,
        },
        {
            alphabet: 'hebrew',
            start: 1488,
            end: 1514,
        },
        {
            alphabet: 'devanagari',
            start: 2309,
            end: 2361,
        },
        {
            alphabet: 'bengali',
            start: 2437,
            end: 2489,
        },
        {
            alphabet: 'thai',
            start: 3585,
            end: 3631,
        },
        {
            alphabet: 'lao',
            start: 3713,
            end: 3759,
        },
        {
            alphabet: 'greek',
            start: 945,
            end: 974,
        },
        {
            alphabet: 'cjk',
            start: 11904,
            end: 12245
        },
    ],
    westernMarkets: [
        "US",
        "CA",
        "GB",
        "JP",
        "FI",
        "IS",
        "LU",
        "PT",
        "ES",
        "NL",
        "BE",
        "FR",
        "IT",
        "CH",
        "AT",
        "DK",
        "SE",
        "NO",
        "PL",
        "DE",
        "BR"
    ],
    markets: [
        "AD",
        "AE",
        "AG",
        "AL",
        "AM",
        "AO",
        "AR",
        "AT",
        "AU",
        "AZ",
        "BA",
        "BB",
        "BD",
        "BE",
        "BF",
        "BG",
        "BH",
        "BI",
        "BJ",
        "BN",
        "BO",
        "BR",
        "BS",
        "BT",
        "BW",
        "BY",
        "BZ",
        "CA",
        "CD",
        "CG",
        "CH",
        "CI",
        "CL",
        "CM",
        "CO",
        "CR",
        "CV",
        "CW",
        "CY",
        "CZ",
        "DE",
        "DJ",
        "DK",
        "DM",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FJ",
        "FM",
        "FR",
        "GA",
        "GB",
        "GD",
        "GE",
        "GH",
        "GM",
        "GN",
        "GQ",
        "GR",
        "GT",
        "GW",
        "GY",
        "HK",
        "HN",
        "HR",
        "HT",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IQ",
        "IS",
        "IT",
        "JM",
        "JO",
        "JP",
        "KE",
        "KG",
        "KH",
        "KI",
        "KM",
        "KN",
        "KR",
        "KW",
        "KZ",
        "LA",
        "LB",
        "LC",
        "LI",
        "LK",
        "LR",
        "LS",
        "LT",
        "LU",
        "LV",
        "LY",
        "MA",
        "MC",
        "MD",
        "ME",
        "MG",
        "MH",
        "MK",
        "ML",
        "MN",
        "MO",
        "MR",
        "MT",
        "MU",
        "MV",
        "MW",
        "MX",
        "MY",
        "MZ",
        "NA",
        "NE",
        "NG",
        "NI",
        "NL",
        "NO",
        "NP",
        "NR",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PG",
        "PH",
        "PK",
        "PL",
        "PS",
        "PT",
        "PW",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "RW",
        "SA",
        "SB",
        "SC",
        "SE",
        "SG",
        "SI",
        "SK",
        "SL",
        "SM",
        "SN",
        "SR",
        "ST",
        "SV",
        "SZ",
        "TD",
        "TG",
        "TH",
        "TJ",
        "TL",
        "TN",
        "TO",
        "TR",
        "TT",
        "TV",
        "TW",
        "TZ",
        "UA",
        "UG",
        "US",
        "UY",
        "UZ",
        "VC",
        "VE",
        "VN",
        "VU",
        "WS",
        "XK",
        "ZA",
        "ZM",
        "ZW"
    ]
}