service: spotify-random-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 900

functions:
  western:
    handler: handler.western
    events:
      - schedule: rate(1 day)
  background:
    handler: handler.background
    events:
      - schedule: rate(1 day)