service: spotify-random-lambda
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  timeout: 900
  memorySize: 2048

# iamRoleStatements:
#   - Effect: Allow
#     Action:
#       - "s3:GetObject"
#       - "s3:PutObject"
#       - "s3:DeleteObject"
#       - "s3:PutObjectAcl"
#       - "s3:ListBucket"
#     Resource:
#       - "arn:aws:s3:::rent-prices"
#       - "arn:aws:s3:::rent-prices/*"

functions:
  background:
    handler: handler.background
    events:
      - schedule: rate(1 day)
  backgroundV2:
    handler: handler.backgroundV2